version: '3'

services:
  db:
    image: postgres:11-alpine
    environment:
      - POSTGRES_DB=easypay
      - POSTGRES_PASSWORD=easypay
    volumes:
      - db_data:/var/lib/postgresql/data

  easypay:
    build: .
    depends_on:
      - db
    environment:
      - DB_DRIVER=org.postgresql.Driver
      - DB_URL=jdbc:postgresql://db:5432/easypay
      - DB_USERNAME=postgres
      - DB_PASSWORD=easypay
      - WAIT_FOR=db:5432
    ports:
      - 8080:8080
      - 9990:9990

volumes:
  db_data:
